---
title: "Music Insights"
author: "Austin Meyer"
output: html_notebook
---

```{r}
install.packages("tidyverse")
library("tidyverse")

survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferances <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")
```

Cleaning-up data titles survey:
```{r}
colnames(survey)[colnames(survey) == "First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "generator_name"
colnames(survey)[colnames(survey) == "What is your pseudonym?" ] <- "pseudonym"
colnames(survey)[colnames(survey) == "Timestamp"] <- "time_submitted"
colnames(survey)[colnames(survey) == "Sex"] <- "sex"
colnames(survey)[colnames(survey) == "Major"] <- "academic_major"
colnames(survey)[colnames(survey) == "Academic Year"] <- "academic_level"
colnames(survey)[colnames(survey) == "Year you were born (YYYY)"] <- "year_born"
colnames(survey)[colnames(survey) == "Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument_list"
colnames(survey)[colnames(survey) == "Artist"] <- "favorite_song_artist"
colnames(survey)[colnames(survey) == "Song"] <- "favorite_song"
colnames(survey)[colnames(survey) == "Link to song (on Youtube or Vimeo)"] <- "favorite_song_link"
```


```{r}
library(tidyr)
library(dplyr)
```

Create New table for person
```{r}
Person <- tibble(pseudonym_generator=survey$pseudonym_generator, pseudonym=survey$pseudonym, sex=survey$sex, year_born=survey$year_born, academic_major=survey$academic_major, academic_level=survey$academic_level, time_submitted=survey$time_submitted)
```

Create new table for favorite song
```{r}
FavoriteSong <- tibble(pseudonym=survey$pseudonym, favorite_song=survey$favorite_song, favorite_song_artist=survey$favorite_song_artist, favorite_song_link=survey$favorite_song_link)
